# -*- coding: utf-8 -*-
"""COM提取复波A/B和策日的具体股票代码列表，对比差异"""
import win32com.client, pythoncom, traceback, os, time

pythoncom.CoInitialize()
excel = None
try:
    excel = win32com.client.DispatchEx("Excel.Application")
    excel.Visible = False
    excel.DisplayAlerts = False
    excel.ScreenUpdating = False

    xlsm = r'D:\@VSwork\VS昭明计划VBA优化\昭明计划VS优化.xlsm'
    print("Opening xlsm...")
    wb = excel.Workbooks.Open(xlsm)
    print(f"Opened: {wb.Name}")

    # Step 1: Generate 复波A/B tables
    # These are generated by routines in 筛选.bas
    # Let me check if sheets already exist
    sheet_names = [ws.Name for ws in wb.Worksheets]
    print(f"Total sheets: {len(sheet_names)}")

    # Check for 复波A and 策日 sheets
    found = {'复波': False, '策日': False}
    for name in sheet_names:
        if '.复波A' in name or '.复波B' in name:
            found['复波'] = True
        if '.策日' in name:
            found['策日'] = True

    print(f"Found existing sheets: 复波={found['复波']}, 策日={found['策日']}")

    # If not found, try to generate them
    if not found['复波'] or not found['策日']:
        print("Generating tables...")
        try:
            excel.Application.Run("IQQQ展擎主前调")
            print("Generation done")
            time.sleep(5)
        except Exception as e:
            print(f"Generation failed: {e}")

    # Refresh sheet names
    sheet_names = [ws.Name for ws in wb.Worksheets]

    # Step 2: Extract stock codes from each table
    result = {}

    for prefix, label in [('.复波A', '复波A'), ('.复波B', '复波B'), ('.策日', '策日')]:
        codes = []
        for name in sheet_names:
            if prefix in name:
                ws = wb.Worksheets(name)
                # Read column A (CIDL codes)
                last_row = ws.UsedRange.Rows.Count
                for r in range(2, last_row + 1):
                    val = ws.Cells(r, 1).Value
                    if val and len(str(val)) >= 6:
                        codes.append(str(val).strip())
                print(f"  {label}: {name} -> {len(codes)} stocks")
                if label not in result:
                    result[label] = []
                result[label].extend(codes)

    # Step 3: Compare
    if '复波A' in result and '复波B' in result and '策日' in result:
        setA = set(result['复波A'])
        setB = set(result['复波B'])
        setC = set(result['策日'])
        setAB = setA | setB

        in_AB_not_C = setAB - setC
        in_C_not_AB = setC - setAB

        print(f"\n=== 对比结果 ===")
        print(f"复波A: {len(setA)} 只")
        print(f"复波B: {len(setB)} 只")
        print(f"复波A+B: {len(setAB)} 只")
        print(f"策日: {len(setC)} 只")
        print(f"在复波A+B但不在策日: {len(in_AB_not_C)} 只")
        print(f"在策日但不在复波A+B: {len(in_C_not_AB)} 只")

        print(f"\n=== 在复波A+B但不在策日的代码 ===")
        for code in sorted(in_AB_not_C):
            print(f"  {code}")

        print(f"\n=== 在策日但不在复波A+B的代码 ===")
        for code in sorted(in_C_not_AB):
            print(f"  {code}")
    else:
        print(f"\n未能获取完整数据")
        print(f"  result keys: {list(result.keys())}")
        for k, v in result.items():
            print(f"  {k}: {len(v)} stocks")

    wb.Close(False)
    print("\nDone")

except Exception as e:
    print(f"Error: {e}")
    traceback.print_exc()
finally:
    if excel:
        excel.Quit()
        pythoncom.CoUninitialize()