with open('_主文档/MC3.3.4_研究日冲策略探索形态.md', 'r', encoding='utf-8') as f:
    content = f.read()

# ===== STEP 1: 〇→一, 一→二, 二→附录, 三→四, 四→五, 五→六 =====
content = content.replace('## 〇、日冲策略总览', '## 一、日冲策略总览')
content = content.replace('### 〇.1 策略定位', '### 1.1 策略定位')
content = content.replace('### 〇.2 现状与瓶颈', '### 1.2 现状与瓶颈')
content = content.replace('### 〇.3 下日冲高概率结论', '### 1.3 下日冲高概率结论')

content = content.replace('## 一、DXZC+DXAB 最小模型验证（全量数据结论）', '## 二、DXZC+DXAB 最小模型验证（全量数据结论）')
content = content.replace('### 1.1 验证概述', '### 2.1 验证概述')
content = content.replace('### 1.2 核心验证结果', '### 2.2 核心验证结果')
content = content.replace('#### 1.2.1 护型排序（全量）', '#### 2.2.1 护型排序（全量）')
content = content.replace('#### 1.2.2 假设验证结论', '#### 2.2.2 假设验证结论')
content = content.replace('### 1.3 普适性验证', '### 2.3 普适性验证')
content = content.replace('#### 1.3.1 分花册验证', '#### 2.3.1 分花册验证')
content = content.replace('#### 1.3.2 个体差异分析', '#### 2.3.2 个体差异分析')
content = content.replace('#### 1.3.3 周线 WXZC+WXAB 验证', '#### 2.3.3 周线 WXZC+WXAB 验证')
content = content.replace('### 1.4 总结与规则', '### 2.4 总结与规则')
content = content.replace('#### 1.4.1 修正后的统一模型规则', '#### 2.4.1 修正后的统一模型规则')
content = content.replace('#### 1.4.2 关键发现', '#### 2.4.2 关键发现')
content = content.replace('#### 1.4.3 核心领悟', '#### 2.4.3 核心领悟')
content = content.replace('### 1.5 五维度深度分析', '### 2.5 五维度深度分析')
content = content.replace('#### 1.5.1 维度一：DXZC数值分级', '#### 2.5.1 维度一：DXZC数值分级')
content = content.replace('#### 1.5.2 维度二：DXAB×DXCD 联动', '#### 2.5.2 维度二：DXAB×DXCD 联动')
content = content.replace('#### 1.5.3 维度三：次日冲高分析', '#### 2.5.3 维度三：次日冲高分析')
content = content.replace('#### 1.5.4 维度四：ZC拐点分析', '#### 2.5.4 维度四：ZC拐点分析')
content = content.replace('#### 1.5.5 维度五：护型变化序列', '#### 2.5.5 维度五：护型变化序列')
content = content.replace('#### 1.5.6 维度六：DXAB×柱排联合形态', '#### 2.5.6 维度六：DXAB×柱排联合形态')
content = content.replace('#### 1.5.7 维度七：DXAB持续天数效应', '#### 2.5.7 维度七：DXAB持续天数效应')
content = content.replace('#### 1.5.8 维度八：DXZA持续时长', '#### 2.5.8 维度八：DXZA持续时长')
content = content.replace('### 1.6 完整模型规则', '### 2.6 完整模型规则')
content = content.replace('#### 1.6.1 五段式DXZC+DXAB操作规则', '#### 2.6.1 五段式DXZC+DXAB操作规则')
content = content.replace('#### 1.6.2 护型变化预警', '#### 2.6.2 护型变化预警')
content = content.replace('#### 1.6.3 拐点操作规则', '#### 2.6.3 拐点操作规则')
content = content.replace('### 1.7 深入探索方向', '### 2.7 深入探索方向')
content = content.replace('#### 1.7.1 已验证的结论', '#### 2.7.1 已验证的结论')
content = content.replace('#### 1.7.2 待验证的细化信号', '#### 2.7.2 待验证的细化信号')
content = content.replace('#### 1.7.3 DXAB与DXZA的持有状态', '#### 2.7.3 DXAB与DXZA的持有状态')
content = content.replace('#### 1.7.4 与现有系统的关系', '#### 2.7.4 与现有系统的关系')

# 二→附录
content = content.replace('## 二、DXZA全周期分类', '## 附录：DXZA全周期分类')
content = content.replace('### 2.1 四前缀分类系统', '### A.1 四前缀分类系统')
content = content.replace('### 2.2 22种状态定义', '### A.2 22种状态定义')
content = content.replace('### 2.3 22种状态统计全表', '### A.3 22种状态统计全表')
content = content.replace('### 2.4 效果评估', '### A.4 效果评估')
content = content.replace('### 2.5 操作指南', '### A.5 操作指南')
content = content.replace('### 2.6 分类系统的实际作用', '### A.6 分类系统的实际作用')
content = content.replace('#### 2.5.1 仓位管理', '#### A.6.1 仓位管理')
content = content.replace('#### 2.5.2 风险预警', '#### A.6.2 风险预警')
content = content.replace('#### 2.5.3 模式应对', '#### A.6.3 模式应对')
content = content.replace('#### 2.5.4 明高率辅助决策', '#### A.6.4 明高率辅助决策')

# 三→四
content = content.replace('## 三、基本条件：日类什么位置会有阳柱', '## 四、基本条件：日类什么位置会有阳柱')
content = content.replace('### 3.1 硬条件', '### 4.1 硬条件')
content = content.replace('### 3.2 趋势背景分类', '### 4.2 趋势背景分类')
content = content.replace('### 3.3 探索问题', '### 4.3 探索问题')
content = content.replace('### 3.4 与现有系统关联', '### 4.4 与现有系统关联')
content = content.replace('### 3.4.1 与日浮仓策略的关系', '#### 4.4.1 与日浮仓策略的关系')
content = content.replace('### 3.4.2 与日冲策略的关系', '#### 4.4.2 与日冲策略的关系')
content = content.replace('### 3.4.3 与周冲策略的关系', '#### 4.4.3 与周冲策略的关系')
content = content.replace('### 3.4.4 与路线图的关系', '#### 4.4.4 与路线图的关系')

# 四→五
content = content.replace('## 四、日周联动', '## 五、日周联动')
content = content.replace('### 4.0 日周结合', '### 5.0 日周结合')
content = content.replace('#### 4.0.1 核心原则', '#### 5.0.1 核心原则')
content = content.replace('#### 4.0.2 镜面对称', '#### 5.0.2 镜面对称')
content = content.replace('#### 4.0.3 日级别介入决策清单', '#### 5.0.3 日级别介入决策清单')
content = content.replace('### 4.1 周←→日映射关系', '### 5.1 周←→日映射关系')
content = content.replace('### 4.2 月基四域→日冲5层', '### 5.2 月基四域→日冲5层')
content = content.replace('### 4.3 日冲5层操作列表', '### 5.3 日冲5层操作列表')
content = content.replace('### 4.4 为什么G级', '### 5.4 为什么G级')
content = content.replace('### 4.5 日层联动', '### 5.5 日层联动')
content = content.replace('#### 4.5.1 原 E/V 21 级体系', '#### 5.5.1 原 E/V 21 级体系')
content = content.replace('#### 4.5.2 首字(金银唏嘘尿屎)', '#### 5.5.2 首字(金银唏嘘尿屎)')
content = content.replace('#### 4.5.3 DXCD护段', '#### 5.5.3 DXCD护段')
content = content.replace('#### 4.5.4 关键启示', '#### 5.5.4 关键启示')
content = content.replace('#### 4.5.5 待验证', '#### 5.5.5 待验证')

# 五→六
content = content.replace('## 五、按形态探索', '## 六、按形态探索')
content = content.replace('### 5.1 探索路径一', '### 6.1 探索路径一')
content = content.replace('### 5.1.1 窄管中蓄力', '### 6.1.1 窄管中蓄力')
content = content.replace('### 5.1.2 窄管中多柱形态', '### 6.1.2 窄管中多柱形态')
content = content.replace('#### 5.1.2.1 最佳形态', '#### 6.1.2.1 最佳形态')
content = content.replace('#### 5.1.2.2 次佳形态', '#### 6.1.2.2 次佳形态')
content = content.replace('#### 5.1.2.3 可接受的阴柱形态', '#### 6.1.2.3 可接受的阴柱形态')
content = content.replace('### 5.1.3 管中多次反弹', '### 6.1.3 管中多次反弹')
content = content.replace('### 5.2 探索路径二', '### 6.2 探索路径二')
content = content.replace('### 5.2.1 基本突破回踩', '### 6.2.1 基本突破回踩')
content = content.replace('### 5.2.2 突破后的启动结构', '### 6.2.2 突破后的启动结构')
content = content.replace('### 5.2.3 潜在四柱栅', '### 6.2.3 潜在四柱栅')
content = content.replace('### 5.2.4 悬阳升连', '### 6.2.4 悬阳升连')
content = content.replace('### 5.3 探索路径三', '### 6.3 探索路径三')
content = content.replace('### 5.3.1 【顺势】触顶后未冲高', '### 6.3.1 【顺势】触顶后未冲高')
content = content.replace('### 5.3.2 【捡漏】触b', '### 6.3.2 【捡漏】触b')
content = content.replace('### 5.3.3 【寻找升排】', '### 6.3.3 【寻找升排】')
content = content.replace('### 5.4 探索路径四', '### 6.4 探索路径四')
content = content.replace('### 5.4.1 偏BSHA 警告', '### 6.4.1 偏BSHA 警告')
content = content.replace('### 5.4.2 偏管警告', '### 6.4.2 偏管警告')
content = content.replace('### 5.4.3 管宽(5,15)', '### 6.4.3 管宽(5,15)')
content = content.replace('### 5.5 探索路径五', '### 6.5 探索路径五')
content = content.replace('### 5.5.1 刚上破DJA', '### 6.5.1 刚上破DJA')
content = content.replace('#### 5.5.1.1 突破回踩', '#### 6.5.1.1 突破回踩')
content = content.replace('#### 5.5.1.2 悬阳升连', '#### 6.5.1.2 悬阳升连')
content = content.replace('### 5.5.2 主升中途回调', '### 6.5.2 主升中途回调')
content = content.replace('### 5.5.3 四柱栅', '### 6.5.3 四柱栅')
content = content.replace('### 5.6 探索路径六', '### 6.6 探索路径六')
content = content.replace('### 5.6.1 鼎', '### 6.6.1 鼎')
content = content.replace('#### 5.6.1.1 鼎分类', '#### 6.6.1.1 鼎分类')
content = content.replace('#### 5.6.1.2 鼎后阴', '#### 6.6.1.2 鼎后阴')
content = content.replace('#### 5.6.1.3 对鼎', '#### 6.6.1.3 对鼎')
content = content.replace('#### 5.6.1.4 鼎的相关规则', '#### 6.6.1.4 鼎的相关规则')
content = content.replace('### 5.6.2 薡', '### 6.6.2 薡')
content = content.replace('### 5.6.3 四柱栅 / 三柱栅', '### 6.6.3 四柱栅 / 三柱栅')
content = content.replace('#### 5.6.3.1 初突破DJC时', '#### 6.6.3.1 初突破DJC时')
content = content.replace('#### 5.6.3.2 久运行于DJC之上时', '#### 6.6.3.2 久运行于DJC之上时')
content = content.replace('#### 5.6.3.3 兼容情况', '#### 6.6.3.3 兼容情况')
content = content.replace('### 5.6.4 管中阴', '### 6.6.4 管中阴')
content = content.replace('### 5.6.5 D1b 特殊形态', '### 6.6.5 D1b 特殊形态')
content = content.replace('### 5.6.6 三视角关系', '### 6.6.6 三视角关系')
content = content.replace('### 5.7 探索路径七', '### 6.7 探索路径七')
content = content.replace('### 5.7.1 【向上突破】', '### 6.7.1 【向上突破】')
content = content.replace('### 5.7.2 【向下突破】', '### 6.7.2 【向下突破】')
content = content.replace('### 5.8 管宽', '### 6.8 管宽')
content = content.replace('### 5.9 DSHA', '### 6.9 DSHA')
content = content.replace('### 5.10 四域日', '### 6.10 四域日')
content = content.replace('### 5.11 关键启示', '### 6.11 关键启示')
content = content.replace('### 十五.6 窄管蓄力验证', '### 6.12 窄管蓄力验证')

# ===== STEP 2: Move appendix to end =====
s_app = content.find('## 附录：DXZA全周期分类')
s_6 = content.find('## 六、按形态探索')
sec_6 = content[s_6:s_app]
sec_app = content[s_app:]
before_6 = content[:s_6]
content = before_6 + sec_6 + '\n\n' + sec_app

# ===== STEP 3: Fix 核心准则 heading =====
content = content.replace('### 核心准则（全量数据验证）', '### 2.0 核心准则（全量数据验证）')

# ===== STEP 4: Fix sub-headings under 2.5 =====
content = content.replace('##### 1.5.1.1 ZC区间划分', '##### 2.5.1.1 ZC区间划分')
content = content.replace('##### 1.5.1.2 修正后的五段式模型', '##### 2.5.1.2 修正后的五段式模型')
content = content.replace('1.5.1.2 的拐点效应表', '2.5.1.2 的拐点效应表')
content = content.replace('##### 1.5.3.1 细分：乙的次日冲高优势', '##### 2.5.3.1 细分：乙的次日冲高优势')
content = content.replace('##### 1.5.5.1 细分：乙的转移概率', '##### 2.5.5.1 细分：乙的转移概率')

# ===== STEP 5: Fix internal references =====
content = content.replace('§1.5.3.1', '§2.5.3.1')
content = content.replace('§1.5.5', '§2.5.5')
content = content.replace('§1.5.6', '§2.5.6')
content = content.replace('§1.5.7', '§2.5.7')
content = content.replace('§一的1.6.3节', '§2.6.3节')
content = content.replace('§〇 日冲策略总览、§十三 日周联动、§十五 按形态探索；§十四 执行框架', '§一 日冲策略总览、§五 日周联动、§六 按形态探索；§4.4 执行框架')
content = content.replace('| #6 寻找日机 | §十四~§十四 |', '| #6 寻找日机 | §六（按形态探索） |')
content = content.replace('| #7 寻找日诱 | §十四（日警）+ 日诱剔除规则 |', '| #7 寻找日诱 | §六（日警）+ 日诱剔除规则 |')
content = content.replace('（来自1.5.7）', '（来自2.5.7）')
content = content.replace('（来自1.5.6）', '（来自2.5.6）')

# ===== STEP 6: Remove orphan # lines =====
content = content.replace('\n#\n\n####', '\n####')
content = content.replace('\n#\n####', '\n####')

with open('_主文档/MC3.3.4_研究日冲策略探索形态.md', 'w', encoding='utf-8') as f:
    f.write(content)
print('All done')